Repository sublimetext-io/docs.sublimetext.io, pull requests merged in 2020-05, with the labels that each got.

#11 implement: missing .nav-links from main theme
  docs/.vuepress/theme/styles/index.styl
Labels: bug, theme

#10 <Key /> component to generate kbd elements from keypresses
  CONTRIBUTING.md
  docs/.vuepress/components/Key.vue
  docs/guide/build-systems/README.md
  docs/guide/customization/key_bindings.md
  docs/guide/editing/README.md
  docs/guide/extensibility/command_palette.md
  docs/guide/extensibility/completions.md
  docs/guide/extensibility/macros.md
  docs/guide/extensibility/plugins.md
  docs/guide/extensibility/snippets.md
  docs/guide/extensibility/syntaxdefs.md
  docs/guide/file-management/navigation.md
  docs/guide/file-management/projects.md
  docs/guide/search-and-replace/multiple.md
  docs/guide/search-and-replace/single.md
  docs/reference/command_palette.md
  docs/reference/comments.md
  docs/reference/keyboard_shortcuts_osx.md
  docs/reference/keyboard_shortcuts_win.md
  docs/reference/settings.md
  docs/reference/symbols.md
Labels: enhancement

#12 Fix missing "Python" link value
  docs/guide/getting-started/basic-concepts.md
Labels: documentation, good first issue
